server:
  #Spring boot项目访问端口
  port: 8080

spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    # 如果是true,则是Topic；如果是false或者默认，则是queue。
    jms:
      pub-sub-domain: false
    pool:
      enabled: false #连接池启动  默认false
#      max-connections: 10 # 最大连接数 默认1
# 使用queue(点对点)方式是，pool.enable要设置为false，默认使用的是queue方式，使用topic(订阅)方式是设置为true,同时要添加spring.jms.pub-sub-domain=true
